# Generated by Django 5.1.7 on 2025-03-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0002_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyprOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.typrowner'),
        ),
    ]
