# Generated by Django 5.1.7 on 2025-03-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0003_typrowner_alter_owner_owner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
