# Generated by Django 5.1.7 on 2025-03-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0004_alter_property_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.district'),
            preserve_default=False,
        ),
    ]
