# Generated by Django 5.1.7 on 2025-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0005_property_city_property_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
